export type Point = { date: string; value: number };
export type DimensionPoint = Point & { dimension_id: number; dimension: string };
export type MetricResponse = {
  metric: string;
  label: string;
  source: 'live' | 'data_mart';
  value?: number;
  series?: Array<Point | DimensionPoint>;
  rows?: Array<Record<string, string | number>>;
  matrix?: Array<{ row_id: number; row: string; column_id: number; column: string; value: number }>;
  as_of?: string;
};
export type InsightCalculation = {
  formula_version: string;
  formula: string;
  current_numerator?: number;
  current_denominator?: number;
  previous_numerator?: number;
  previous_denominator?: number;
  absolute_gate: number;
  relative_gate_percent: number;
  result: number;
  indicator?: string;
};
export type InsightItem = {
  key: string;
  label: string;
  direction: 'worsening' | 'improving' | 'neutral';
  unit: string;
  current: number;
  previous: number;
  absolute_change: number;
  relative_change_percent: number | null;
  percentage_point_change: number | null;
  materiality_score: number;
  comparison_text: string;
  narrative: string;
  contributor?: { dimension_id: number; label: string; delta: number } | null;
  evidence_target: 'ticket' | 'asset' | 'licence' | 'change' | 'problem';
  source: 'data_mart';
  as_of: string | null;
  calculation: InsightCalculation;
};
export type InsightResponse = {
  formula_version: string;
  horizon_days: number;
  cutoff: string;
  generated_at: string;
  summary: string;
  insights: InsightItem[];
  suppressed: Array<{ key: string; code: string; message: string }>;
  indicators: Array<{ key: string; metric: string; label: string; severity: 'informational'; value: number }>;
  readiness: { ready_metrics: number; total_metrics: number; required_snapshots: number; metrics: Array<{ metric: string; completed: number; required: number; ready: boolean; state: string }> };
};
export type WidgetType = 'kpi' | 'line' | 'bar' | 'donut' | 'table' | 'detail_table' | 'matrix' | 'attention' | 'insight';
export type WidgetDefinition = { id: string; metric: string; type: WidgetType; title: string; palette: import('./palettes').WidgetPaletteKey; w: number; h: number; x?: number; y?: number };
export type DashboardDefinition = { version: number; dateRangeDays: number; refreshMinutes: number; filters: { groupId: number | null }; widgets: WidgetDefinition[] };
export type SavedDashboard = { id: number | null; name: string; definition: DashboardDefinition; date_mod: string | null };
export type DashboardSummary = { id: number; name: string; is_active: boolean; date_mod: string | null };
export type DashboardTemplate = { key: string; name: string; description: string };
export type DashboardWorkspace = { dashboard: SavedDashboard; dashboards: DashboardSummary[]; templates: DashboardTemplate[] };
export type ReportSchedule = { id: number; name: string; dashboard_definitions_id: number; format: 'pdf' | 'csv'; frequency: 'daily' | 'weekly' | 'monthly'; send_hour: number; weekday: number | null; monthday: number | null; timezone: string; recipients: string[]; is_active: boolean; next_run_at: string; last_run_at: string | null };
