export type Point = { date: string; value: number };
export type DimensionPoint = Point & { dimension_id: number; dimension: string };
export type MetricResponse = {
  metric: string;
  label: string;
  source: 'live' | 'data_mart';
  value?: number;
  series?: Array<Point | DimensionPoint>;
  rows?: Array<Record<string, string | number>>;
  matrix?: Array<{ row_id: number; row: string; column_id: number; column: string; value: number }>;
  as_of?: string;
};
export type WidgetType = 'kpi' | 'line' | 'bar' | 'donut' | 'table' | 'detail_table' | 'matrix' | 'attention' | 'insight';
export type WidgetDefinition = { id: string; metric: string; type: WidgetType; title: string; palette: import('./palettes').WidgetPaletteKey; w: number; h: number };
export type DashboardDefinition = { version: number; dateRangeDays: number; refreshMinutes: number; filters: { groupId: number | null }; widgets: WidgetDefinition[] };
export type SavedDashboard = { id: number | null; name: string; definition: DashboardDefinition; date_mod: string | null };
export type DashboardSummary = { id: number; name: string; is_active: boolean; date_mod: string | null };
export type DashboardTemplate = { key: string; name: string; description: string };
export type DashboardWorkspace = { dashboard: SavedDashboard; dashboards: DashboardSummary[]; templates: DashboardTemplate[] };
export type ReportSchedule = { id: number; name: string; dashboard_definitions_id: number; format: 'pdf' | 'csv'; frequency: 'daily' | 'weekly' | 'monthly'; send_hour: number; weekday: number | null; monthday: number | null; timezone: string; recipients: string[]; is_active: boolean; next_run_at: string; last_run_at: string | null };
